from django.urls import path
from .views import *
from .dokumente_pdf import mayday_plakat_pdf, notrollen_plakat_pdf, dokument_checkliste_pdf
from .dokumente_views import (
    dokument_items_get, dokument_item_add, dokument_item_update,
    dokument_item_delete, dokument_reset,
    dok_standard_list, dok_standard_speichern, dok_standard_laden,
    dok_standard_loeschen, dok_standard_default,
    boot_dokument_get, boot_dokument_toggle,
)
from .schaden_views import (
    schaden_neu, schaden_bearbeiten, schaden_loeschen,
    schaden_status, schaden_bild_loeschen,
)
from .schaden_pdf import schaden_gesamt_pdf, schaden_einzel_pdf

urlpatterns = [
    path('detail/<int:pk>/', toern_detail, name='toern_detail'),  # Detailseite
    path('anmeldung/<int:pk>/', toern_anmeldung, name='toern_anmeldung'),  # Anmeldeseite
    path('anbieter/', anbieter_dashboard, name='anbieter_dashboard'),
    path('create/', toern_create, name='toern_create'),
    path('edit/<int:pk>/', toern_edit, name='toern_edit'),
    path('status/<int:pk>/', toern_status_update, name='toern_status_update'),
    path('privat/<int:pk>/', toern_privat_toggle, name='toern_privat_toggle'),
    path("<int:toern_id>/crew/", crew_dashboard, name="crew_dashboard"),
    path("crew/", crew_overview, name="crew_overview"),
    path("toern/<int:toern_id>/kabine/anfragen/", kabinenpartner_anfragen, name="kabinenpartner_anfragen"),
    path("kabine/<int:wunsch_id>/antwort/", kabinenpartner_antwort, name="kabinenpartner_antwort"),
    path("toern/<int:toern_id>/praeferenzen/", praeferenzen_speichern, name="praeferenzen_speichern"),
    path("<int:toern_id>/skipper/", skipper_dashboard, name="skipper_dashboard"),
    path("toern/<int:toern_id>/kabine-update/", kabine_update, name="kabine_update"),
    path("toern/<int:toern_id>/auto-assign/", auto_assign, name="auto_assign"),
    path("toern/<int:toern_id>/fixieren/<uuid:user_id>/", teilnahme_boot_fixieren, name="teilnahme_boot_fixieren"),
    path("boot/<int:boot_id>/assign-skipper/", boot_skipper_assign, name="boot_skipper_assign"),
    path("toern/<int:toern_id>/reset/", reset_zuteilung, name="reset_zuteilung"),
    path("warteliste/bestaetigen/<int:teilnahme_id>/", warteliste_bestaetigen, name="warteliste_bestaetigen"),
    path("<int:toern_id>/fix/", zuteilung_fixieren, name="zuteilung_fixieren"),
    path("warteliste/ablehnen/<int:teilnahme_id>/", warteliste_ablehnen, name="warteliste_ablehnen"),
    path("<int:toern_id>/daten/", teilnahme_daten_edit, name="teilnahme_daten_edit"),
    path("teilnehmer/bestaetigen/<int:teilnahme_id>/", teilnehmer_bestaetigen, name="teilnehmer_bestaetigen"),
    path("teilnehmer/zuruecksetzen/<int:teilnahme_id>/", teilnehmer_zuruecksetzen, name="teilnehmer_zuruecksetzen"),
    path("teilnehmer/ablehnen/<int:teilnahme_id>/", teilnehmer_ablehnen, name="teilnehmer_ablehnen"),
    path("<int:toern_id>/absagen/", teilnahme_absagen, name="teilnahme_absagen"),
    path("<int:pk>/loeschen/", toern_delete, name="toern_delete"),
    path("<int:pk>/abschliessen/", toern_status_abschliessen, name="toern_status_abschliessen"),
    path("boot/<int:boot_id>/abschluss/", boot_abschluss_update, name="boot_abschluss_update"),
    path("<int:pk>/foto-links/", toern_foto_links_update, name="toern_foto_links_update"),
    path("<int:toern_id>/boot/", boot_dashboard, name="boot_dashboard"),
    path("gegenstand/<int:gegenstand_id>/take/", take_gegenstand, name="take_gegenstand"),
    path("<int:toern_id>/packitem/add/", add_packitem, name="add_packitem"),
    path("packitem/<int:item_id>/update/", update_packitem, name="update_packitem"),
    path("packitem/<int:item_id>/delete/", delete_packitem, name="delete_packitem"),
    path("packitem/<int:item_id>/toggle/", toggle_packitem, name="toggle_packitem"),
    path("<int:toern_id>/bootitem/add/", add_boot_item, name="add_boot_item"),
    path("bootitem/<int:item_id>/update/", update_boot_item, name="update_boot_item"),
    path("bootitem/<int:item_id>/delete/", delete_boot_item, name="delete_boot_item"),
    path("gegenstand/<int:gegenstand_id>/reduce/", reduce_gegenstand, name="reduce_gegenstand"),
    path("crewlist/<int:boot_id>/pdf/", crewlist_pdf, name="crewlist_pdf"),
    path("boot/<int:boot_id>/mayday/pdf/", mayday_plakat_pdf, name="mayday_plakat_pdf"),
    path("boot/<int:boot_id>/notrollen/pdf/", notrollen_plakat_pdf, name="notrollen_plakat_pdf"),
    path("boot/<int:boot_id>/checkliste/<str:typ>/pdf/", dokument_checkliste_pdf, name="dokument_checkliste_pdf"),
    # Schadensprotokoll
    path("boot/<int:boot_id>/schaden/neu/", schaden_neu, name="schaden_neu"),
    path("boot/<int:boot_id>/schaden/pdf/", schaden_gesamt_pdf, name="schaden_gesamt_pdf"),
    path("schaden/<int:meldung_id>/bearbeiten/", schaden_bearbeiten, name="schaden_bearbeiten"),
    path("schaden/<int:meldung_id>/loeschen/", schaden_loeschen, name="schaden_loeschen"),
    path("schaden/<int:meldung_id>/status/", schaden_status, name="schaden_status"),
    path("schaden/<int:meldung_id>/pdf/", schaden_einzel_pdf, name="schaden_einzel_pdf"),
    path("schaden/bild/<int:bild_id>/loeschen/", schaden_bild_loeschen, name="schaden_bild_loeschen"),
    path("boot/<int:boot_id>/checkliste/<str:typ>/abhaken/", boot_dokument_get, name="boot_dokument_get"),
    path("boot/<int:boot_id>/checkliste/item/<int:eintrag_id>/toggle/", boot_dokument_toggle, name="boot_dokument_toggle"),
    path("<int:toern_id>/dokument/item/add/", dokument_item_add, name="dokument_item_add"),
    path("<int:toern_id>/dokument/item/<int:item_id>/update/", dokument_item_update, name="dokument_item_update"),
    path("<int:toern_id>/dokument/item/<int:item_id>/delete/", dokument_item_delete, name="dokument_item_delete"),
    path("<int:toern_id>/dokument/reset/", dokument_reset, name="dokument_reset"),
    path("dokument/standards/", dok_standard_list, name="dok_standard_list"),
    path("<int:toern_id>/dokument/standard/speichern/", dok_standard_speichern, name="dok_standard_speichern"),
    path("<int:toern_id>/dokument/standard/laden/", dok_standard_laden, name="dok_standard_laden"),
    path("dokument/standards/<int:standard_id>/loeschen/", dok_standard_loeschen, name="dok_standard_loeschen"),
    path("dokument/standards/<int:standard_id>/default/", dok_standard_default, name="dok_standard_default"),
    path("<int:toern_id>/dokument/<str:typ>/", dokument_items_get, name="dokument_items_get"),
    path("<int:toern_id>/teilnehmerliste/pdf/", teilnehmerliste_pdf, name="teilnehmerliste_pdf"),
    path("<int:toern_id>/vorlage/revier/", packl_revier_set, name="packl_revier_set"),
    path("<int:toern_id>/vorlage/item/add/", vorlage_item_add, name="vorlage_item_add"),
    path("<int:toern_id>/vorlage/item/<int:item_id>/update/", vorlage_item_update, name="vorlage_item_update"),
    path("<int:toern_id>/vorlage/item/<int:item_id>/delete/", vorlage_item_delete, name="vorlage_item_delete"),
    path("<int:toern_id>/vorlage/anwenden/", vorlage_anwenden, name="vorlage_anwenden"),
    path("packliste/standards/", packl_standard_list, name="packl_standard_list"),
    path("<int:toern_id>/vorlage/standard/speichern/", packl_standard_speichern, name="packl_standard_speichern"),
    path("<int:toern_id>/vorlage/standard/laden/", packl_standard_laden, name="packl_standard_laden"),
    path("packliste/standards/<int:standard_id>/loeschen/", packl_standard_loeschen, name="packl_standard_loeschen"),
    path("packliste/standards/<int:standard_id>/default/", packl_standard_default, name="packl_standard_default"),
    path("<int:toern_id>/vorlage/<str:typ>/", vorlage_items_get, name="vorlage_items_get"),
    path("<int:toern_id>/mahlzeit/add/", add_mahlzeit, name="add_mahlzeit"),
    path("mahlzeit/<int:mahlzeit_id>/delete/", delete_mahlzeit, name="delete_mahlzeit"),
    path("<int:toern_id>/erinnerung/senden/", send_reminder_toern, name="send_reminder_toern"),
    path("beschreibung/generieren/", toern_beschreibung_generieren, name="toern_beschreibung_generieren"),
    path("<int:toern_id>/pinnwand/add/", pinnwand_nachricht_erstellen, name="pinnwand_nachricht_erstellen"),
    path("pinnwand/<int:nachricht_id>/loeschen/", pinnwand_nachricht_loeschen, name="pinnwand_nachricht_loeschen"),
    path("<int:toern_id>/mitfahrt/add/", mitfahrangebot_erstellen, name="mitfahrangebot_erstellen"),
    path("mitfahrt/<int:eintrag_id>/loeschen/", mitfahrangebot_loeschen, name="mitfahrangebot_loeschen"),
    # Mitfahrtanfrage
    path("mitfahrt/anfrage/<int:angebot_id>/senden/", mitfahrt_anfrage_senden, name="mitfahrt_anfrage_senden"),
    path("mitfahrt/anfrage/<int:anfrage_id>/antworten/", mitfahrt_anfrage_antworten, name="mitfahrt_anfrage_antworten"),
    path("mitfahrt/anfrage/<int:anfrage_id>/zurueckziehen/", mitfahrt_anfrage_zurueckziehen, name="mitfahrt_anfrage_zurueckziehen"),
    # Tagesplan
    path("<int:toern_id>/boot/<int:boot_id>/tagesplan/aufgabe/add/", tagesaufgabe_add, name="tagesaufgabe_add"),
    path("tagesplan/aufgabe/<int:aufgabe_id>/delete/", tagesaufgabe_delete, name="tagesaufgabe_delete"),
    path("<int:toern_id>/boot/<int:boot_id>/tagesplan/impuls/add/", tagesimpuls_add, name="tagesimpuls_add"),
    path("tagesplan/impuls/<int:impuls_id>/delete/", tagesimpuls_delete, name="tagesimpuls_delete"),
    path("<int:toern_id>/boot/<int:boot_id>/tagesplan/recht/<int:teilnahme_id>/", tagesplan_recht_toggle, name="tagesplan_recht_toggle"),
    path("<int:toern_id>/boot/<int:boot_id>/tagesplan/pdf/", tagesplan_pdf, name="tagesplan_pdf"),
    path("<int:pk>/tagesimpulse/toggle/", toern_tagesimpulse_toggle, name="toern_tagesimpulse_toggle"),
    path("<int:toern_id>/praeferenz-modus/", praeferenz_modus_setzen, name="praeferenz_modus_setzen"),
    path("<int:toern_id>/boot/<int:boot_id>/tagesplan/mahlzeit/add/", tagesplan_mahlzeit_add, name="tagesplan_mahlzeit_add"),
    path("<int:toern_id>/boot/<int:boot_id>/tagesplan/thema/", tagesthema_set, name="tagesthema_set"),
    path("<int:toern_id>/boot/<int:boot_id>/tagesplan/rezept-suche/", rezept_suche, name="tagesplan_rezept_suche"),
    path("<int:toern_id>/boot/<int:boot_id>/tagesplan/kochplan/pdf/", tagesplan_kochplan_pdf, name="tagesplan_kochplan_pdf"),
    # Einkaufsliste
    path("<int:toern_id>/boot/<int:boot_id>/einkaufsliste/generieren/", einkaufsliste_generieren, name="einkaufsliste_generieren"),
    path("<int:toern_id>/boot/<int:boot_id>/einkaufsliste/add/",        einkaufsliste_add,        name="einkaufsliste_add"),
    path("<int:toern_id>/boot/<int:boot_id>/einkaufsliste/aufteilen/",  einkaufsliste_aufteilen,  name="einkaufsliste_aufteilen"),
    path("<int:toern_id>/boot/<int:boot_id>/einkaufsliste/status/",     einkaufsliste_status,     name="einkaufsliste_status"),
    path("einkaufsliste/<int:eintrag_id>/toggle/",                       einkaufsliste_toggle,     name="einkaufsliste_toggle"),
    path("einkaufsliste/<int:eintrag_id>/delete/",                       einkaufsliste_delete,     name="einkaufsliste_delete"),
    path("einkaufsliste/<int:eintrag_id>/reaktivieren/",                 einkaufsliste_reaktivieren, name="einkaufsliste_reaktivieren"),
    path("<int:toern_id>/einkaufsvorlage/",                              einkaufsvorlage_get,      name="einkaufsvorlage_get"),
    path("<int:toern_id>/einkaufsvorlage/add/",                          einkaufsvorlage_add,      name="einkaufsvorlage_add"),
    path("<int:toern_id>/einkaufsvorlage/<int:item_id>/update/",         einkaufsvorlage_update,   name="einkaufsvorlage_update"),
    path("<int:toern_id>/einkaufsvorlage/<int:item_id>/delete/",         einkaufsvorlage_delete,   name="einkaufsvorlage_delete"),
    path("<int:toern_id>/einkaufsvorlage/als-standard/",                 einkaufsvorlage_als_standard, name="einkaufsvorlage_als_standard"),
]