# Generated by Django 6.0.3 on 2026-03-22 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boote', '0001_initial'),
        ('toern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.CharField(max_length=200)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beteiligt', models.ManyToManyField(related_name='beteiligte_ausgaben', to='toern.teilnahme')),
                ('bezahlt_von', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bezahlt_ausgaben', to='toern.teilnahme')),
                ('boot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausgaben', to='boote.boot')),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausgaben', to='toern.toern')),
            ],
        ),
    ]
