# Generated by Django 6.0.3 on 2026-07-02 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('toern', '0025_toern_skipper_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausgabe',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='ausgabe',
            name='erstellt_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erfasste_ausgaben', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TopfAusgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.CharField(max_length=200)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topf_ausgaben', to=settings.AUTH_USER_MODEL)),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topf_ausgaben', to='toern.toern')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
