# Generated by Django 6.0.3 on 2026-03-15 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boote', '0001_initial'),
        ('finance', '0001_initial'),
        ('toern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausgabe',
            name='beteiligt',
            field=models.ManyToManyField(related_name='beteiligte_ausgaben', to='toern.teilnahme'),
        ),
        migrations.AddField(
            model_name='ausgabe',
            name='bezahlt_von',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bezahlt_ausgaben', to='toern.teilnahme'),
        ),
        migrations.AddField(
            model_name='ausgabe',
            name='boot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausgaben', to='boote.boot'),
        ),
        migrations.AddField(
            model_name='ausgabe',
            name='toern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausgaben', to='toern.toern'),
        ),
    ]
