# Generated by Django 6.0.3 on 2026-07-31 17:58

import django.db.models.deletion
import finance.models
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_ausgabe_options_ausgabe_erstellt_von_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topfausgabe',
            name='kategorie',
            field=models.CharField(choices=[('versicherung', 'Skipper-Versicherungen'), ('anreise', 'Anreise & Unterkunft'), ('treibstoff', 'Bootstreibstoff'), ('hafen', 'Hafen, Liegeplatz & Abgaben'), ('charter', 'Charter-Nebenkosten'), ('verpflegung', 'Verpflegung'), ('crew', 'Crew-Ausstattung'), ('ausruestung', 'Ausrüstung, Material & Reparatur'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=20),
        ),
        migrations.CreateModel(
            name='TopfBeleg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bild', imagekit.models.fields.ProcessedImageField(upload_to=finance.models.beleg_upload_to)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ausgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belege', to='finance.topfausgabe')),
                ('hochgeladen_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hochgeladene_belege', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
