# Generated by Django 5.2.13 on 2026-09-25 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boote', '0010_boot_charterbasis_email_boot_charterbasis_name'),
        ('finance', '0003_topfausgabe_kategorie_topfbeleg'),
        ('toern', '0040_briefing_struktur_und_vorlagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausgleichszahlung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erhaltene_ausgleichszahlungen', to='toern.teilnahme')),
                ('boot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausgleichszahlungen', to='boote.boot')),
                ('erfasst_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erfasste_ausgleichszahlungen', to=settings.AUTH_USER_MODEL)),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausgleichszahlungen', to='toern.toern')),
                ('von', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geleistete_ausgleichszahlungen', to='toern.teilnahme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
