# Generated by Django 5.2.13 on 2026-09-30 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_ausgleichszahlung'),
        ('toern', '0040_briefing_struktur_und_vorlagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Umlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.CharField(max_length=200)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bezahlt_von', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bezahlte_umlagen', to='toern.teilnahme')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erfasste_umlagen', to=settings.AUTH_USER_MODEL)),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umlagen', to='toern.toern')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UmlageAnteil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('schon_gegeben', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('anteil', models.DecimalField(decimal_places=2, max_digits=8)),
                ('beglichen_am', models.DateTimeField(blank=True, null=True)),
                ('beglichen_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beglichene_umlage_anteile', to=settings.AUTH_USER_MODEL)),
                ('teilnahme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umlage_anteile', to='toern.teilnahme')),
                ('umlage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anteile', to='finance.umlage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('umlage', 'teilnahme'), name='umlage_anteil_einmal_pro_person')],
            },
        ),
    ]
