# Generated by Django 6.0.3 on 2026-03-15 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gegenstand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('menge', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mitbringer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menge', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PersönlicherGegenstand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('menge', models.PositiveIntegerField(default=1)),
                ('erledigt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Einkaufspunkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('menge', models.CharField(blank=True, max_length=50)),
                ('erledigt', models.BooleanField(default=False)),
                ('boot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einkaufsliste', to='boote.boot')),
            ],
        ),
    ]
