# Generated by Django 6.0.3 on 2026-03-15 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boote', '0001_initial'),
        ('logistik', '0001_initial'),
        ('toern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='einkaufspunkt',
            name='toern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einkaufsliste', to='toern.toern'),
        ),
        migrations.AddField(
            model_name='einkaufspunkt',
            name='verantwortlich',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toern.teilnahme'),
        ),
        migrations.AddField(
            model_name='gegenstand',
            name='boot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gegenstaende', to='boote.boot'),
        ),
        migrations.AddField(
            model_name='gegenstand',
            name='toern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gegenstaende', to='toern.toern'),
        ),
        migrations.AddField(
            model_name='mitbringer',
            name='gegenstand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitbringer', to='logistik.gegenstand'),
        ),
        migrations.AddField(
            model_name='mitbringer',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toern.teilnahme'),
        ),
        migrations.AddField(
            model_name='persönlichergegenstand',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persoenliche_packliste', to='toern.teilnahme'),
        ),
    ]
