# Generated by Django 6.0.3 on 2026-04-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persönlichergegenstand',
            name='ist_vom_boot',
            field=models.BooleanField(default=False),
        ),
    ]
