# Generated by Django 6.0.3 on 2026-06-06 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boote', '0006_alter_boot_laenge_alter_boot_tiefe'),
        ('logistik', '0002_persönlichergegenstand_ist_vom_boot'),
        ('toern', '0014_teilnahme_lebensmittelunvertraeglichkeiten_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahlzeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('typ', models.CharField(choices=[('fruehstueck', 'Frühstück'), ('mittag', 'Mittagessen'), ('abend', 'Abendessen'), ('snack', 'Snack')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('boot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahlzeiten', to='boote.boot')),
                ('kochverantwortlich', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahlzeiten', to='toern.teilnahme')),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahlzeiten', to='toern.toern')),
            ],
            options={
                'ordering': ['datum', 'typ'],
            },
        ),
    ]
