# Generated by Django 6.0.3 on 2026-06-23 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boote', '0008_remove_boot_foto_links'),
        ('logistik', '0003_mahlzeit'),
        ('toern', '0020_tagesplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahlzeit',
            name='typ',
            field=models.CharField(choices=[('fruehstueck', 'Frühstück'), ('mittag', 'Mittagessen'), ('abend', 'Abendessen'), ('essen_gehen', 'Essen gehen'), ('snack', 'Snack')], max_length=20),
        ),
        migrations.CreateModel(
            name='Tagesaufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('typ', models.CharField(choices=[('abwasch', 'Abwasch'), ('navigation', 'Navigation'), ('abfahrtsprotokoll', 'Abfahrtsprotokoll'), ('einkauf', 'Einkauf / Proviant'), ('hafenwache', 'Hafenwache'), ('reinigung', 'Reinigung / Aufräumen'), ('sonstiges', 'Sonstiges')], default='abwasch', max_length=30)),
                ('beschreibung', models.CharField(blank=True, max_length=200)),
                ('boot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagesaufgaben', to='boote.boot')),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagesaufgaben', to='toern.toern')),
                ('verantwortlich', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aufgaben', to='toern.teilnahme')),
            ],
            options={
                'ordering': ['datum', 'typ'],
            },
        ),
        migrations.CreateModel(
            name='Tagesimpuls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('slot', models.CharField(choices=[('vormittag', 'Vormittag'), ('nachmittag', 'Nachmittag')], max_length=20)),
                ('thema', models.CharField(max_length=200)),
                ('boot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagesimpulse', to='boote.boot')),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagesimpulse', to='toern.toern')),
                ('verantwortlich', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulse', to='toern.teilnahme')),
            ],
            options={
                'ordering': ['datum', 'slot'],
                'unique_together': {('boot', 'toern', 'datum', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='TagesplanBearbeitungsrecht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagesplan_rechte', to='boote.boot')),
                ('teilnahme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagesplan_rechte', to='toern.teilnahme')),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagesplan_rechte', to='toern.toern')),
            ],
            options={
                'unique_together': {('boot', 'toern', 'teilnahme')},
            },
        ),
    ]
