# Generated by Django 6.0.3 on 2026-06-23 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boote', '0008_remove_boot_foto_links'),
        ('logistik', '0004_tagesplan'),
        ('toern', '0021_mitfahrtanfrage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagesthema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('thema', models.CharField(blank=True, max_length=300)),
                ('boot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagesthemen', to='boote.boot')),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagesthemen', to='toern.toern')),
            ],
            options={
                'unique_together': {('boot', 'toern', 'datum')},
            },
        ),
    ]
