# Generated by Django 6.0.3 on 2026-06-23 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0005_tagesthema'),
        ('rezepte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahlzeit',
            name='rezept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahlzeiten', to='rezepte.rezept'),
        ),
    ]
