# Generated by Django 6.0.3 on 2026-06-23 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boote', '0008_remove_boot_foto_links'),
        ('logistik', '0006_mahlzeit_rezept'),
        ('toern', '0022_tagesimpulse_aktiv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EinkaufslistenEintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('menge', models.CharField(blank=True, max_length=100)),
                ('kategorie', models.CharField(choices=[('obst_gemuese', 'Obst & Gemüse'), ('fleisch_fisch', 'Fleisch & Fisch'), ('milch_kase', 'Milch, Käse & Eier'), ('brot', 'Brot & Backwaren'), ('nudeln_reis', 'Nudeln, Reis & Hülsenfrüchte'), ('konserven', 'Konserven & Saucen'), ('gewurze_ol', 'Gewürze, Öle & Essig'), ('getranke', 'Getränke'), ('tiefkuhl', 'Tiefkühlprodukte'), ('haushalt', 'Haushalt & Hygiene'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=20)),
                ('quelle', models.CharField(default='manuell', max_length=20)),
                ('rezept_info', models.CharField(blank=True, max_length=500)),
                ('erledigt', models.BooleanField(default=False)),
                ('erledigt_am', models.DateTimeField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('boot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einkaufs_eintraege', to='boote.boot')),
                ('einkaufer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='einkaufs_items', to='toern.teilnahme')),
                ('erledigt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einkaufs_eintraege', to='toern.toern')),
            ],
            options={
                'ordering': ['kategorie', 'name'],
            },
        ),
    ]
