# Generated by Django 6.0.3 on 2026-07-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0007_einkaufslisteneintrag'),
    ]

    operations = [
        migrations.AddField(
            model_name='persönlichergegenstand',
            name='ist_skipper',
            field=models.BooleanField(default=False),
        ),
    ]
