# Generated by Django 6.0.3 on 2026-07-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0008_persönlichergegenstand_ist_skipper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagesaufgabe',
            name='typ',
            field=models.CharField(choices=[('abwasch', 'Abwasch'), ('navigation', 'Navigation'), ('abfahrtsprotokoll', 'Abfahrtsprotokoll'), ('einkauf', 'Einkauf / Proviant'), ('backschaft', 'Backschaft'), ('reinigung', 'Reinigung / Aufräumen'), ('sonstiges', 'Sonstiges')], default='abwasch', max_length=30),
        ),
    ]
