# Generated by Django 6.0.3 on 2026-07-11 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0010_hafenwache_zu_sonstiges'),
        ('toern', '0031_teilnahme_boot_fixiert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='einkaufslisteneintrag',
            name='archiviert',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EinkaufsStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='einkaufs_standard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EinkaufsStandardEintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('menge_template', models.CharField(blank=True, max_length=100)),
                ('kategorie', models.CharField(choices=[('obst_gemuese', 'Obst & Gemüse'), ('fleisch_fisch', 'Fleisch & Fisch'), ('milch_kase', 'Milch, Käse & Eier'), ('brot', 'Brot & Backwaren'), ('nudeln_reis', 'Nudeln, Reis & Hülsenfrüchte'), ('konserven', 'Konserven & Saucen'), ('gewurze_ol', 'Gewürze, Öle & Essig'), ('getranke', 'Getränke'), ('tiefkuhl', 'Tiefkühlprodukte'), ('haushalt', 'Haushalt & Hygiene'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=20)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eintraege', to='logistik.einkaufsstandard')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EinkaufsVorlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='einkaufs_vorlage', to='toern.toern')),
            ],
        ),
        migrations.CreateModel(
            name='EinkaufsVorlageEintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('menge_template', models.CharField(blank=True, max_length=100)),
                ('kategorie', models.CharField(choices=[('obst_gemuese', 'Obst & Gemüse'), ('fleisch_fisch', 'Fleisch & Fisch'), ('milch_kase', 'Milch, Käse & Eier'), ('brot', 'Brot & Backwaren'), ('nudeln_reis', 'Nudeln, Reis & Hülsenfrüchte'), ('konserven', 'Konserven & Saucen'), ('gewurze_ol', 'Gewürze, Öle & Essig'), ('getranke', 'Getränke'), ('tiefkuhl', 'Tiefkühlprodukte'), ('haushalt', 'Haushalt & Hygiene'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=20)),
                ('vorlage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eintraege', to='logistik.einkaufsvorlage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
