# Generated by Django 5.2.13 on 2026-09-23 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boote', '0010_boot_charterbasis_email_boot_charterbasis_name'),
        ('logistik', '0011_einkaufslisteneintrag_archiviert_einkaufsstandard_and_more'),
        ('toern', '0040_briefing_struktur_und_vorlagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EinkaufslistenSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('anlass', models.CharField(default='aufraeumen', max_length=50)),
                ('daten', models.JSONField(default=list)),
                ('zurueckgespielt_am', models.DateTimeField(blank=True, null=True)),
                ('boot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einkaufs_snapshots', to='boote.boot')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einkaufs_snapshots', to='toern.toern')),
            ],
            options={
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
