# Generated by Django 5.2.13 on 2026-09-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0012_einkaufslistensnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='einkaufslisteneintrag',
            name='manuelle_menge',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
