# Generated by Django 5.2.13 on 2026-09-23 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0012_einkaufslistensnapshot'),
        ('toern', '0040_briefing_struktur_und_vorlagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bordvorrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bordvorrat', to='toern.toern')),
            ],
        ),
        migrations.CreateModel(
            name='BordvorratEintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notiz', models.CharField(blank=True, max_length=200)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('vorrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eintraege', to='logistik.bordvorrat')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
