# Generated by Django 6.0.3 on 2026-03-22 16:28

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('geschlecht', models.CharField(blank=True, choices=[('m', 'Männlich'), ('w', 'Weiblich'), ('d', 'Divers')], default='d', max_length=10)),
                ('geburtsdatum', models.DateField(blank=True, null=True)),
                ('geburtsort', models.CharField(blank=True, max_length=100)),
                ('nationalitaet', models.CharField(blank=True, max_length=50)),
                ('identifikationstyp', models.CharField(choices=[('pers', 'Personalausweis'), ('reise', 'Reisepass')], default='pers', max_length=100)),
                ('passnummer', models.CharField(blank=True, max_length=50)),
                ('strasse', models.CharField(blank=True, max_length=100)),
                ('plz', models.CharField(blank=True, max_length=5)),
                ('ort', models.CharField(blank=True, max_length=50)),
                ('telefonnummer', models.CharField(blank=True, max_length=20)),
                ('profilbild', models.ImageField(blank=True, null=True, upload_to=accounts.models.profilbild_upload_path)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lizenz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ausstellungsdatum', models.DateField()),
                ('ablaufdatum', models.DateField(blank=True, null=True)),
                ('dokument_vorne', models.ImageField(blank=True, null=True, upload_to='accounts/lizenz_dokumente/')),
                ('dokument_hinten', models.ImageField(blank=True, null=True, upload_to='accounts/lizenz_dokumente/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lizenzen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ersteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erstellt_notizen', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notizen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
