# Generated by Django 6.0.3 on 2026-03-22 18:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilbild_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
