# Generated by Django 6.0.3 on 2026-03-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geburtsort',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='geschlecht',
            field=models.CharField(choices=[('m', 'Männlich'), ('w', 'Weiblich'), ('d', 'Divers')], default='d', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='identifikationstyp',
            field=models.CharField(choices=[('pers', 'Personalausweis'), ('reise', 'Reisepass')], default='pers', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='profilbild',
            field=models.ImageField(blank=True, null=True, upload_to='profilbilder/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='plz',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='strasse',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
