# Generated by Django 6.0.3 on 2026-04-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profilbild_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geburtsland',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='land',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
