# Generated by Django 6.0.3 on 2026-03-07 16:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilbild',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.profilbild_upload_path),
        ),
    ]
