# Generated by Django 6.0.3 on 2026-03-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profilbild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='geschlecht',
            field=models.CharField(blank=True, choices=[('m', 'Männlich'), ('w', 'Weiblich'), ('d', 'Divers')], default='d', max_length=10),
        ),
    ]
