# Generated by Django 6.0.3 on 2026-06-20 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuellerSeemeilenEintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.CharField(max_length=200)),
                ('meilen', models.PositiveIntegerField()),
                ('datum', models.DateField()),
                ('revier', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuelle_seemeilen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datum'],
            },
        ),
    ]
