# Generated by Django 6.0.3 on 2026-03-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email_alter_user_geschlecht'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lizenz',
            name='dokument',
        ),
        migrations.AddField(
            model_name='lizenz',
            name='dokument_hinten',
            field=models.ImageField(blank=True, null=True, upload_to='lizenz_dokumente/{self.user.username}/'),
        ),
        migrations.AddField(
            model_name='lizenz',
            name='dokument_vorne',
            field=models.ImageField(blank=True, null=True, upload_to='lizenz_dokumente/{self.user.username}/'),
        ),
    ]
