# Generated by Django 5.2.13 on 2026-09-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_andacht'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zahlung_iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='user',
            name='zahlung_kontoinhaber',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kontoinhaber'),
        ),
        migrations.AddField(
            model_name='user',
            name='zahlung_paypal',
            field=models.CharField(blank=True, help_text='PayPal.Me-Name oder PayPal-E-Mail-Adresse', max_length=254, verbose_name='PayPal'),
        ),
        migrations.AddField(
            model_name='user',
            name='zahlung_wero',
            field=models.CharField(blank=True, help_text='Dein Wero-Zahlungslink', max_length=254, verbose_name='Wero'),
        ),
    ]
