# Generated by Django 6.0.3 on 2026-03-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_lizenz_dokument_lizenz_dokument_hinten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lizenz',
            name='dokument_hinten',
            field=models.ImageField(blank=True, null=True, upload_to='lizenz_dokumente/'),
        ),
        migrations.AlterField(
            model_name='lizenz',
            name='dokument_vorne',
            field=models.ImageField(blank=True, null=True, upload_to='lizenz_dokumente/'),
        ),
    ]
