# Generated by Django 6.0.3 on 2026-03-22 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charterunternehmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('internetseite', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefonnummer', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('typ', models.CharField(max_length=100)),
                ('Hafen', models.CharField(blank=True, max_length=100)),
                ('Hafen_googlemaps', models.CharField(blank=True, max_length=100)),
                ('baujahr', models.PositiveIntegerField(blank=True, null=True)),
                ('laenge', models.FloatField(blank=True, null=True)),
                ('tiefe', models.FloatField(blank=True, null=True)),
                ('preis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bild_boot', models.ImageField(blank=True, null=True, upload_to='boote/bilder/')),
                ('charterunternehmen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boote', to='boote.charterunternehmen')),
            ],
        ),
        migrations.CreateModel(
            name='Kabine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('betten', models.PositiveIntegerField(default=2)),
                ('boot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kabinen', to='boote.boot')),
            ],
        ),
    ]
