# Generated by Django 6.0.3 on 2026-03-28 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boote', '0001_initial'),
        ('toern', '0004_remove_toern_boote'),
    ]

    operations = [
        migrations.AddField(
            model_name='boot',
            name='toern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boote', to='toern.toern'),
        ),
    ]
