# Generated by Django 6.0.3 on 2026-03-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boot',
            name='bild_boot',
            field=models.ImageField(blank=True, null=True, upload_to='boote/'),
        ),
    ]
