# Generated by Django 6.0.3 on 2026-03-28 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boote', '0002_boot_toern'),
        ('toern', '0004_remove_toern_boote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boot',
            name='toern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boote', to='toern.toern'),
        ),
    ]
