# Generated by Django 6.0.3 on 2026-03-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boote', '0003_alter_boot_toern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boot',
            old_name='Hafen',
            new_name='hafen',
        ),
        migrations.RenameField(
            model_name='boot',
            old_name='Hafen_googlemaps',
            new_name='hafen_googlemaps',
        ),
    ]
