# Generated by Django 6.0.3 on 2026-04-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boote', '0004_rename_hafen_boot_hafen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boot',
            name='laenge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='boot',
            name='tiefe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
