# Generated by Django 6.0.3 on 2026-04-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boote', '0005_alter_boot_laenge_alter_boot_tiefe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boot',
            name='laenge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boot',
            name='tiefe',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
