# Generated by Django 6.0.3 on 2026-06-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boote', '0006_alter_boot_laenge_alter_boot_tiefe'),
    ]

    operations = [
        migrations.AddField(
            model_name='boot',
            name='foto_download_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='boot',
            name='foto_upload_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='boot',
            name='logbuch_pdf',
            field=models.FileField(blank=True, null=True, upload_to='boote/logbuch/'),
        ),
        migrations.AddField(
            model_name='boot',
            name='skipper_meilen',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
