# Generated by Django 6.0.3 on 2026-07-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boote', '0008_remove_boot_foto_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='boot',
            name='funkrufzeichen',
            field=models.CharField(blank=True, max_length=20, verbose_name='Funkrufzeichen (Call Sign)'),
        ),
        migrations.AddField(
            model_name='boot',
            name='mmsi',
            field=models.CharField(blank=True, max_length=9, verbose_name='MMSI'),
        ),
    ]
