# Generated by Django 6.0.3 on 2026-07-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boote', '0009_boot_funkrufzeichen_boot_mmsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='boot',
            name='charterbasis_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Charterbasis E-Mail (für Schadensprotokoll)'),
        ),
        migrations.AddField(
            model_name='boot',
            name='charterbasis_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Charterbasis (Name)'),
        ),
    ]
