# Generated by Django 6.0.3 on 2026-06-23 18:37

import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kategorie', models.CharField(choices=[('fruehstueck', 'Frühstück'), ('hauptgericht', 'Hauptgericht'), ('snack', 'Snack / Kleines'), ('dessert', 'Dessert'), ('sonstiges', 'Sonstiges')], default='hauptgericht', max_length=30)),
                ('bild', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='rezepte/')),
                ('zubereitungszeit', models.PositiveSmallIntegerField(default=30, help_text='Minuten')),
                ('portionen', models.PositiveSmallIntegerField(default=4)),
                ('tipps', models.TextField(blank=True)),
                ('getraenk', models.CharField(blank=True, max_length=200)),
                ('quelle_url', models.URLField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rezepte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='RezeptSchritt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('rezept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schritte', to='rezepte.rezept')),
            ],
            options={
                'ordering': ['nummer'],
            },
        ),
        migrations.CreateModel(
            name='RezeptZutat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('menge', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('rezept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zutaten', to='rezepte.rezept')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RezeptStern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rezept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sterne', to='rezepte.rezept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezept_sterne', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('rezept', 'user')},
            },
        ),
    ]
