# Generated by Django 6.0.3 on 2026-03-15 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boote', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Toern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('startdatum', models.DateTimeField()),
                ('enddatum', models.DateTimeField()),
                ('revier', models.CharField(max_length=200)),
                ('preis_pro_person', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nebenkosten', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('ANMELDUNG_OFFEN', 'Anmeldung offen'), ('ANMELDUNG_GESCHLOSSEN', 'Anmeldung geschlossen'), ('ZUTEILUNG_VORGESCHLAGEN', 'Zuweisung vorgeschlagen'), ('VEROEFFENTLICHT', 'Veröffentlicht'), ('ABGESCHLOSSEN', 'Abgeschlossen')], default='DRAFT', max_length=30)),
                ('boote', models.ManyToManyField(related_name='toerns', to='boote.boot')),
            ],
        ),
        migrations.CreateModel(
            name='Teilnahme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolle', models.CharField(choices=[('skipper', 'Skipper'), ('co_skp', 'Co-Skipper'), ('crew', 'Crew')], max_length=20)),
                ('status', models.CharField(choices=[('angemeldet', 'Angemeldet'), ('warteliste', 'Warteliste'), ('bestaetigt', 'Bestätigt')], default='angemeldet', max_length=20)),
                ('notizen', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ausschlussliste', models.ManyToManyField(blank=True, related_name='ausgeschlossen_teilnahmen', to=settings.AUTH_USER_MODEL)),
                ('boot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teilnahmen', to='boote.boot')),
                ('kabine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teilnahmen', to='boote.kabine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teilnahmen', to=settings.AUTH_USER_MODEL)),
                ('wunschpartner', models.ManyToManyField(blank=True, related_name='wunschpartner_teilnahmen', to=settings.AUTH_USER_MODEL)),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teilnahmen', to='toern.toern')),
            ],
            options={
                'unique_together': {('user', 'toern')},
            },
        ),
    ]
