# Generated by Django 6.0.3 on 2026-03-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toern',
            name='anmeldeschluss',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
