# Generated by Django 6.0.3 on 2026-03-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toern',
            name='beschreibung',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='toern',
            name='bild_toern',
            field=models.ImageField(blank=True, null=True, upload_to='toerns/'),
        ),
        migrations.AddField(
            model_name='toern',
            name='kurzbeschreibung',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
