# Generated by Django 6.0.3 on 2026-03-28 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boote', '0001_initial'),
        ('toern', '0002_toern_anmeldeschluss'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teilnahme',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='gesegelte_meilen',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='seglerische_erfahrung',
            field=models.CharField(choices=[('1', 'Landratte'), ('2', 'Mitsegler*in'), ('3', 'Crew'), ('4', 'Steuermann*frau'), ('5', 'Skipper*in')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='toern',
            name='anbieter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angebotene_toerns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='teilnahme',
            constraint=models.UniqueConstraint(fields=('user', 'toern'), name='unique_user_toern'),
        ),
    ]
