# Generated by Django 6.0.3 on 2026-03-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0003_alter_teilnahme_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toern',
            name='boote',
        ),
    ]
