# Generated by Django 6.0.3 on 2026-03-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0004_remove_toern_boote'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnahme',
            name='teilnahmebedingungen_akzeptiert',
            field=models.BooleanField(default=False),
        ),
    ]
