# Generated by Django 6.0.3 on 2026-04-12 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0005_teilnahme_teilnahmebedingungen_akzeptiert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KabinenWunsch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kabinen_anfragen_gesendet', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kabinen_anfragen_erhalten', to=settings.AUTH_USER_MODEL)),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toern.toern')),
            ],
            options={
                'unique_together': {('toern', 'from_user', 'to_user')},
            },
        ),
    ]
