# Generated by Django 6.0.3 on 2026-04-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0007_crewpraeferenz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teilnahme',
            name='rolle',
            field=models.CharField(choices=[('skipper', 'Skipper'), ('coskipper', 'Co-Skipper'), ('crew', 'Crew')], max_length=20),
        ),
    ]
