# Generated by Django 6.0.3 on 2026-04-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0008_alter_teilnahme_rolle'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnahme',
            name='allergien',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='essgewohnheiten',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='notfallkontakt_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='notfallkontakt_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='notfallkontakt_telefon',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='tshirt_groesse',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5),
        ),
    ]
