# Generated by Django 6.0.3 on 2026-05-03 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0010_alter_toern_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootPacklisteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('menge', models.IntegerField(default=1)),
                ('beschreibung', models.TextField(blank=True)),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toern.toern')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalPacklisteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('menge', models.IntegerField(default=1)),
                ('beschreibung', models.TextField(blank=True)),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toern.toern')),
            ],
        ),
    ]
