# Generated by Django 6.0.3 on 2026-05-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0011_bootpacklistetemplate_personalpacklistetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalpacklistetemplate',
            name='toern',
        ),
        migrations.DeleteModel(
            name='BootPacklisteTemplate',
        ),
        migrations.DeleteModel(
            name='PersonalPacklisteTemplate',
        ),
    ]
