# Generated by Django 6.0.3 on 2026-05-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0011_bootpacklistetemplate_personalpacklistetemplate'),
    ]

    operations = [
        # Use SeparateDatabaseAndState so the database operation is safe (IF EXISTS)
        # while Django's migration state is updated correctly regardless.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        "DROP TABLE IF EXISTS toern_personalpacklistetemplate",
                        "DROP TABLE IF EXISTS toern_bootpacklistetemplate",
                    ],
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='personalpacklistetemplate',
                    name='toern',
                ),
                migrations.DeleteModel(
                    name='BootPacklisteTemplate',
                ),
                migrations.DeleteModel(
                    name='PersonalPacklisteTemplate',
                ),
            ],
        ),
    ]
