# Generated by Django 6.0.3 on 2026-05-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0012_packlistevorlage_packlistevorlageEintrag'),
        ('toern', '0012_remove_personalpacklistetemplate_toern_and_more'),
    ]

    operations = [
    ]
