# Generated by Django 6.0.3 on 2026-06-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0013_merge_20260510_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnahme',
            name='lebensmittelunvertraeglichkeiten',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teilnahme',
            name='essgewohnheiten',
            field=models.CharField(blank=True, choices=[('alles', 'Kein Fleischverzicht'), ('vegetarisch', 'Vegetarisch'), ('vegan', 'Vegan')], default='', max_length=20),
        ),
    ]
