# Generated by Django 6.0.3 on 2026-06-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0015_erinnerungsmaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='toern',
            name='fotogalerie_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='toern',
            name='logbuch_pdf',
            field=models.FileField(blank=True, null=True, upload_to='toern/logbuch/'),
        ),
    ]
