# Generated by Django 6.0.3 on 2026-06-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0019_mitfahrangebot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toern',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Entwurf'), ('ANMELDUNG_OFFEN', 'Anmeldung offen'), ('ANMELDUNG_GESCHLOSSEN', 'Anmeldung geschlossen'), ('ZUTEILUNG_VORGESCHLAGEN', 'Zuweisung vorgeschlagen'), ('ZUTEILUNG_FIXIERT', 'Zuteilung abgeschlossen'), ('ABGESCHLOSSEN', 'Abgeschlossen')], default='DRAFT', max_length=30),
        ),
    ]
