# Generated by Django 6.0.3 on 2026-06-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0021_mitfahrtanfrage'),
    ]

    operations = [
        migrations.AddField(
            model_name='toern',
            name='tagesimpulse_aktiv',
            field=models.BooleanField(default=True, verbose_name='Tagesthema & Impulse aktiv'),
        ),
    ]
