# Generated by Django 6.0.3 on 2026-07-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0024_packliste_toern_revier'),
    ]

    operations = [
        migrations.AddField(
            model_name='toern',
            name='skipper_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Budget für Skipper/Co-Skipper (z.B. Crewshirts, Fahrtkosten, Crew-Essen)', max_digits=8, verbose_name='Skipper-Topf (€)'),
        ),
    ]
