# Generated by Django 6.0.3 on 2026-07-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0026_toern_privat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packlistevorlage',
            name='typ',
            field=models.CharField(choices=[('personal', 'Persönlich'), ('boot', 'Boot'), ('skipper', 'Skipper')], max_length=10),
        ),
    ]
