# Generated by Django 6.0.3 on 2026-07-04 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0027_alter_packlistevorlage_typ'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PacklisteStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('typ', models.CharField(choices=[('personal', 'Persönlich'), ('boot', 'Boot'), ('skipper', 'Skipper')], max_length=10)),
                ('ist_default', models.BooleanField(default=False, help_text='Wird bei neuen Törns automatisch als Start-Vorlage verwendet (max. einer pro Typ)')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packliste_standards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'typ', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PacklisteStandardEintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('menge', models.PositiveIntegerField(default=1)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eintraege', to='toern.packlistestandard')),
            ],
        ),
    ]
