# Generated by Django 6.0.3 on 2026-07-04 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0028_packlistestandard_packlistestandardeintrag'),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumentVorlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('uebernahme', 'Charterübernahme'), ('ablegen', 'Bevor wir ablegen'), ('anlegen', 'Nach dem Anlegen'), ('rueckgabe', 'Rückgabe')], max_length=20)),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokument_vorlagen', to='toern.toern')),
            ],
            options={
                'unique_together': {('toern', 'typ')},
            },
        ),
        migrations.CreateModel(
            name='DokumentEintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sektion', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('reihenfolge', models.PositiveIntegerField(default=0)),
                ('vorlage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eintraege', to='toern.dokumentvorlage')),
            ],
            options={
                'ordering': ['reihenfolge', 'id'],
            },
        ),
    ]
