# Generated by Django 5.2.13 on 2026-07-04 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0029_dokumentvorlage_dokumenteintrag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumentStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('typ', models.CharField(choices=[('uebernahme', 'Charterübernahme'), ('ablegen', 'Bevor wir ablegen'), ('anlegen', 'Nach dem Anlegen'), ('rueckgabe', 'Rückgabe')], max_length=20)),
                ('ist_default', models.BooleanField(default=False, help_text='Wird bei neuen Törns automatisch als Start-Checkliste verwendet (max. einer pro Typ)')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokument_standards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'typ', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DokumentStandardEintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sektion', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('reihenfolge', models.PositiveIntegerField(default=0)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eintraege', to='toern.dokumentstandard')),
            ],
            options={
                'ordering': ['reihenfolge', 'id'],
            },
        ),
    ]
