# Generated by Django 5.2.13 on 2026-07-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0030_dokumentstandard_dokumentstandardeintrag'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnahme',
            name='boot_fixiert',
            field=models.BooleanField(default=False, help_text='Vom Skipper ans Boot gepinnt — die Auto-Zuteilung verschiebt diese Person nicht'),
        ),
    ]
