# Generated by Django 6.0.3 on 2026-07-11 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0031_teilnahme_boot_fixiert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packlistevorlage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='packlistevorlage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packliste_vorlagen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='packlistevorlage',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('toern', 'typ'), name='uniq_packlvorlage_toern_typ_shared'),
        ),
        migrations.AddConstraint(
            model_name='packlistevorlage',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('toern', 'typ', 'user'), name='uniq_packlvorlage_toern_typ_user'),
        ),
    ]
