# Generated by Django 6.0.3 on 2026-07-12 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boote', '0009_boot_funkrufzeichen_boot_mmsi'),
        ('toern', '0033_skipper_vorlage_persoenlich'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumentAbhakstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erledigt', models.BooleanField(default=False)),
                ('erledigt_am', models.DateTimeField(blank=True, null=True)),
                ('boot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokument_abhakstatus', to='boote.boot')),
                ('eintrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abhakstatus', to='toern.dokumenteintrag')),
                ('erledigt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('boot', 'eintrag')},
            },
        ),
    ]
