# Generated by Django 6.0.3 on 2026-07-12 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boote', '0010_boot_charterbasis_email_boot_charterbasis_name'),
        ('toern', '0034_dokumentabhakstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schadensmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, verbose_name='Was ist kaputt')),
                ('ort', models.CharField(max_length=200, verbose_name='Wo am Boot')),
                ('schweregrad', models.PositiveSmallIntegerField(choices=[(1, '1 – Kosmetisch / unwesentlich'), (2, '2 – Gering'), (3, '3 – Spürbar'), (4, '4 – Erheblich'), (5, '5 – Sicherheitskritisch / nicht fahrtüchtig')], default=3)),
                ('beschreibung', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('behoben', 'Behoben'), ('gemeldet', 'An Basis gemeldet')], default='offen', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('boot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schaeden', to='boote.boot')),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_schaeden', to=settings.AUTH_USER_MODEL)),
                ('geaendert_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geaenderte_schaeden', to=settings.AUTH_USER_MODEL)),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schaeden', to='toern.toern')),
            ],
            options={
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Schadensbild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bild', models.ImageField(upload_to='schaeden/%Y/%m/')),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True)),
                ('meldung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilder', to='toern.schadensmeldung')),
            ],
            options={
                'ordering': ['hochgeladen_am'],
            },
        ),
    ]
