# Generated by Django 5.2.13 on 2026-09-07 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toern', '0035_schadensmeldung_schadensbild'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rundmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betreff', models.CharField(max_length=200)),
                ('text', models.TextField(help_text='Darf Bausteine wie {{vorname}} enthalten.')),
                ('meeting_link', models.URLField(blank=True)),
                ('termin_start', models.DateTimeField(blank=True, null=True)),
                ('termin_ende', models.DateTimeField(blank=True, null=True)),
                ('termin_titel', models.CharField(blank=True, max_length=200)),
                ('termin_ort', models.CharField(blank=True, help_text="z.B. 'Online' oder ein Treffpunkt.", max_length=200)),
                ('anhang', models.FileField(blank=True, null=True, upload_to='rundmail/%Y/%m/')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('gesendet', 'Gesendet')], default='entwurf', max_length=10)),
                ('empfaenger_count', models.PositiveIntegerField(default=0)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('gesendet_am', models.DateTimeField(blank=True, null=True)),
                ('absender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rundmails', to=settings.AUTH_USER_MODEL)),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rundmails', to='toern.toern')),
            ],
            options={
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
