# Generated by Django 5.2.13 on 2026-09-08 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefing', '0001_initial'),
        ('toern', '0036_rundmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefingAuswahl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktiv', models.BooleanField(default=True)),
                ('reihenfolge', models.PositiveIntegerField(default=0)),
                ('baustein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toern_auswahl', to='briefing.briefingbaustein')),
                ('toern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefing_auswahl', to='toern.toern')),
            ],
            options={
                'ordering': ['reihenfolge', 'id'],
                'unique_together': {('toern', 'baustein')},
            },
        ),
    ]
