BASIS_PACKLISTE = [
    ("Reisepass / Ausweis", 1),
    ("Auslandskrankenversicherung", 1),
    ("Segeljacke / Regenjacke", 1),
    ("Pullover / Fleece", 2),
    ("Longsleever", 2),
    ("Unterwäsche", 7),
    ("T-Shirts", 7),
    ("Hosen / Jeans", 2),
    ("Jogginghose / bequeme Hose", 1),
    ("Shorts / leichte Hose", 2),
    ("Badesachen", 2),
    ("Badetuch", 1),
    ("Duschtrockentuch", 1),
    ("Sonnencreme", 1),
    ("Sonnenbrille", 1),
    ("Kopfbedeckung / Cap", 1),
    ("Segelhandschuhe / Fahrradhandschuhe", 1),
    ("Segelschuhe / Schuhe mit heller Sohle", 1),
    ("Flip Flops", 1),
    ("Persönliche Medikamente", 1),
    ("Kulturbeutel", 1),
    ("Handtuch", 1),
    ("Waschzeug (biologisch abbaubar)", 1),
    ("Schmutzwäschebeutel", 1),
    ("Taschenlampe / Stirnlampe", 1),
    ("Powerbank / Ladekabel", 1),
]

BOOT_STANDARD_LISTE = [
    ("Wäscheleine", 1),
    ("Wäscheklammern", 30),
    ("French Press", 1),
    ("Angelzeug", 1),
    ("Musikbox", 1),
    ("Spiele", 1),
    ("Taucherbrille", 2),
    ("Schnorchel", 2),
    ("Flossen", 2),
    ("Rei aus der Tube", 1),
    ("Lichterkette", 1),
    ("Bänsel", 1),
    ("Kamera", 1),
    ("Infomaterial", 1),
    ("Notfallpässe", 1),
]