BASIS_PACKLISTE = [
    ("Reisepass / Ausweis", 1),
    ("Auslandskrankenversicherung", 1),
    ("Krankenkassenkarte", 1),
    ("EC-Karte/Kreditkarte", 1),
    ("Eigene Segelscheine", 1),
    ("Meilenbuch wenn vorhanden", 1),
    ("ca. 200,00 € für Norfälle", 1),
    ("Taschenmesser/Multifunktionsmesser", 1),
    ("Unterwäsche", 7),
    ("T-Shirts", 7),
    ("Hosen / Jeans", 2),
    ("Shorts / leichte Hose", 2),
    ("Jogginghose / bequeme Hose", 1),
    ("Pullover / Fleece", 2),
    ("Longsleever", 2),
    ("Badesachen", 2),
    ("Badetuch", 1),
    ("Kopfbedeckung / Cap - mit Sportband", 2),
    ("Sonnencreme", 1),
    ("Sonnenbrille", 1),
    ("Segeljacke / Regenjacke", 1),
    ("Segelhandschuhe / Fahrradhandschuhe", 1),
    ("Segelschuhe / Schuhe mit heller Sohle", 1),
    ("Flip Flops", 1),
    ("Kulturbeutel", 1),
    ("Zahnbürste/Pasta", 1),
    ("Waschzeug (biologisch abbaubar)", 1),
    ("Duschtrockentuch", 1),
    ("Handtuch", 1),
    ("Persönliche Medikamente", 1),
    ("Medikamente gegen Seekrankheit", 1),
    ("Mückenabwehr spray", 1),
    ("Labello/Creme", 1),
    ("Schmutzwäschebeutel", 1),
    ("Taschenlampe / Stirnlampe", 1),
    ("Powerbank / Ladekabel", 1),
    
]

BOOT_STANDARD_LISTE = [
    ("Wäscheleine", 1),
    ("Wäscheklammern aus Holz", 30),
    ("scharfe Küchenmesser", 1),
    ("schärfer für Küchenmesser", 1),
    ("Hygienespry - Sagrotan", 1),
    ("Ökologische Handseife - Toilette", 1),
    ("Verschlussklammern Lebensmittel", 5),
    ("Aufbewahrungsdosen Lebensmittel", 5),
    ("Gewürze Mediteran", 5),
    ("French Press", 1),
    ("Angelzeug", 1),
    ("Musikbox", 1),
    ("Spiele", 1),
    ("Taucherbrille", 2),
    ("Schnorchel", 2),
    ("Flossen", 2),
    ("Rei aus der Tube", 1),
    ("Lichterkette", 1),
    ("Bänsel", 1),
    ("Kamera", 1),
    ("Infomaterial", 1),
    ("Notfallpässe", 1),
]