# Generated by Django 5.2.13 on 2026-07-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andacht', '0002_andacht_kontext_andacht_geschichte_quelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='andacht',
            name='veroeffentlicht',
            field=models.BooleanField(default=False, help_text='Im Andachtsbuch für alle eingeloggten Nutzer sichtbar'),
        ),
        migrations.AddField(
            model_name='andacht',
            name='veroeffentlicht_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
