# Generated by Django 6.0.3 on 2026-06-24 19:35

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knoten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField()),
                ('bild', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='segelwissen/knoten/')),
                ('schwierigkeitsgrad', models.CharField(choices=[('leicht', 'Leicht'), ('mittel', 'Mittel'), ('schwer', 'Schwer')], default='mittel', max_length=10)),
                ('reihenfolge', models.PositiveSmallIntegerField(default=0, help_text='Sortierreihenfolge (aufsteigend)')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Knoten',
                'verbose_name_plural': 'Knoten',
                'ordering': ['reihenfolge', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Segelinformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('bild', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='segelwissen/infos/')),
                ('kategorie', models.CharField(choices=[('wetter', 'Wetter'), ('seemannschaft', 'Seemannschaft'), ('navigation', 'Navigation'), ('sicherheit', 'Sicherheit'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=20)),
                ('reihenfolge', models.PositiveSmallIntegerField(default=0)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Segelinformation',
                'verbose_name_plural': 'Segelinformationen',
                'ordering': ['reihenfolge', 'titel'],
            },
        ),
        migrations.CreateModel(
            name='Segelvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True)),
                ('youtube_url', models.URLField(help_text='YouTube-URL (z. B. https://www.youtube.com/watch?v=...)')),
                ('reihenfolge', models.PositiveSmallIntegerField(default=0)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Segelvideo',
                'verbose_name_plural': 'Segelvideos',
                'ordering': ['reihenfolge', 'titel'],
            },
        ),
    ]
