# Generated by Django 5.2.13 on 2026-09-08 19:07

import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefingBaustein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('kategorie', models.CharField(choices=[('kommunikation', 'Kommunikation & Kommando'), ('orientierung', 'Orientierung an Bord'), ('sicherheit', 'Sicherheit'), ('leinen', 'Leinen & Knoten'), ('ablegen', 'Ablegen'), ('anlegen', 'Anlegen'), ('segeln', 'Unter Segeln'), ('bordalltag', 'Leben an Bord'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=20)),
                ('text', models.TextField()),
                ('bild', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='briefing/')),
                ('ist_standard', models.BooleanField(default=False, help_text='Wird bei neuen Törns automatisch ins Briefing übernommen')),
                ('reihenfolge', models.PositiveSmallIntegerField(default=0)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefing_bausteine', to=settings.AUTH_USER_MODEL)),
                ('zuletzt_bearbeitet_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Briefing-Baustein',
                'verbose_name_plural': 'Briefing-Bausteine',
                'ordering': ['kategorie', 'reihenfolge', 'id'],
            },
        ),
    ]
