# Generated by Django 5.2.13 on 2026-09-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefing', '0003_markup_in_standardbausteinen'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefingbaustein',
            name='bild_position',
            field=models.CharField(choices=[('unten', 'Unter dem Text'), ('oben', 'Über dem Text'), ('links', 'Links neben dem Text'), ('rechts', 'Rechts neben dem Text')], default='unten', help_text='Wo das Bild relativ zum Text steht — im PDF und in der Leseansicht', max_length=10),
        ),
    ]
